authentication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/urls.py
from django.urls import path
from .import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('secret/', views.secret1, name='secret'),
    path('secret2/', views.Secret2.as_view(), name='secret2'),

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms



# class SignupForm()

core/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

def home(request):
    count = User.objects.count()
    return render(request, 'home.html', {'count': count})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:home')
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def secret1(request):
    return render(request, 'secret.html')

class Secret2(LoginRequiredMixin, TemplateView):
    template_name = 'secret2.html'

templates/base.html
<html>
    <head>
        <title>
            {% block title %}Base HTML file{% endblock %}
        </title>
    </head>
    <body>
        <h1>My site</h1>
        <hr>
        <a href="{% url 'core:home' %}">Home</a> /
        <a href="{% url 'core:secret' %}">Secret</a> /
        <a href="{% url 'core:secret2' %}">Secret 2</a> /
        <a href="{% url 'core:signup' %}">Signup</a>  / 
        {% if user.is_authenticated %}
            <a href="{% url 'password_change' %}">Change password</a>  / 
            <a href="{% url 'logout' %}">Logout</a> 
        {% else %}
            <a href="{% url 'login' %}">Login</a> /
        {% endif %}
        <hr>
        {% block content %}
        {% endblock %}  
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Homepage{% endblock %}


{% block content %}
    {% if user.is_authenticated %}    
        <p>Hey there! Hello {{ user.username }}</p>
    {% endif %}
    <p>Total registered user to your site: <strong>{{ count }}</strong></p>
{% endblock %}

templates/secret.html
{% extends 'base.html' %}

{% block title %}secret 1{% endblock %}

{% block content %}
    <h1>Secret page</h1>
{% endblock %}

templates/secret2.html
{% extends 'base.html' %}

{% block title %}secret 1{% endblock %}

{% block content %}
    <h1>Secret page</h1>
{% endblock %}